apiVersion: apps/v1

kind: Deployment

metadata:

  name: myapp

spec:

  selector:

    matchLabels:

      run: myapp

  replicas: 1

  template:

    metadata:

      labels:

        run: myapp

    spec:

      containers:

      - name: myapp

        image: killivinay69/myapp

        ports:

        - containerPort: 80
---
apiVersion: v1

kind: Service

metadata:

  name: myapp

spec:

  type: NodePort

  selector:

    run: myapp

  ports:

  - port: 80

    targetPort: 80
